export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";

export const FETCH_USERS = "FETCH_USERS";
export const DELETE_USER = "DELETE_USER";
export const CREATE_USER = "CREATE_USER";

export const FETCH_STORIES = "FETCH_STORIES";
export const DELETE_STORY = "DELETE_STORY";
export const CREATE_STORY = "CREATE_STORY";
